# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Formatting (pre-commit)

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install clang-format-10
        run: sudo apt-get install clang-format-10
      - name: Install black
        run: sudo -H pip3 install black
      - name: Install shfmt
        run: |
          wget -O /tmp/go.tgz https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf /tmp/go.tgz
          sudo ln -s ../go/bin/go /usr/local/bin/go
          sudo GOPATH=/usr/local/go go install mvdan.cc/sh/v3/cmd/shfmt@latest
          sudo ln -s ../go/bin/shfmt /usr/local/bin/shfmt
      - uses: pre-commit/action@v2.0.3
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit
